### ISSUE TITLE
Version not icrementing

### ISSUE THREAD

**Issue by uottoni** [reecetech/version-increment#39]
Every time i run my workflow, i get the same version.
The log says:
⚠️ No previous release version identified in git tags
ℹ️ The current normal version is 0.0.0
and ends with:
ℹ️ The new version is 0.0.1
 Sorry my bad english, i'm learning...
Here is my worklfow code:

```
name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          use_api: true
          scheme: semver
          increment: patch
          release_branch: master
      - name: Use version
        run: echo "Calculated version:${{ steps.version.outputs.version }} - ${{ steps.version.outputs.prefixed-version }}"
```

**Comment by ps-jay** [comment]
Hi @uottoni,

Your english is fine 👍 

At the end of your workflow, you need to "release" (otherwise known as "publish" or "tag") the version

For example, similar to what can be seen [here](https://github.com/reecetech/version-increment/blob/95aaf0c/.github/workflows/test-and-release.yml#L153):
```
      - name: Release version
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        with:
          draft: false
          prerelease: false
          tag_name: "${{ steps.version.outputs.version }}"
 ```

This means if the workflow is running on the default branch, then place a `git tag` on the commit that is used for the workflow - the tag will be named after the version detected (in your case, `0.0.1` to begin with)

Hope that helps!
