### ISSUE TITLE
Support "v" prefix in incremented version

### ISSUE THREAD

**Issue by thekaveman** [reecetech/version-increment#8]
Hey there 👋 this looks like a great Action!

I see in the [lookup](https://github.com/reecetech/version-increment/blob/main/version-lookup.sh#L37), any `v` prefix in the latest tag is stripped:

```bash
# detect current version - removing "v" from start of tag if it exists
current_version="$( ... | sed 's/^v//g' | ... )"
```

This makes the increment math way easier!

I wonder if it would be possible to support adding the `v` prefix back, after the [new version is created](https://github.com/reecetech/version-increment/blob/main/version-increment.sh#L66), if it was there in the first place?

**Comment by ps-jay** [comment]
Yup, can look at that ..

I think I'd make it an optional flag, rather than automatic

e.g.
```yaml
        with:
          scheme: semver
          increment: patch
          v_prefix: true   # defaults to false
```

I hope that would suit
